-- =============================================
-- 자격증 시드 데이터
-- =============================================

INSERT INTO certifications (id, name, category, organization, website, description, tags) VALUES
-- IT
('engineer-info-processing', '정보처리기사', 'IT', '한국산업인력공단', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '정보시스템 개발, 운영, 유지보수 전반에 관한 국가기술자격', ARRAY['국가자격','정보처리','개발','IT','기사']),
('engineer-info-processing-industrial', '정보처리산업기사', 'IT', '한국산업인력공단', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '정보시스템 개발, 운영에 관한 산업기사 수준 국가기술자격', ARRAY['국가자격','정보처리','개발','IT','산업기사']),
('sqld', 'SQLD (SQL 개발자)', 'IT', '한국데이터산업진흥원', 'https://www.dataq.or.kr/', 'SQL을 활용한 데이터베이스 개발 및 관리 능력 검증', ARRAY['SQL','데이터베이스','DB','민간자격']),
('sqlp', 'SQLP (SQL 전문가)', 'IT', '한국데이터산업진흥원', 'https://www.dataq.or.kr/', 'SQL 고급 활용 및 데이터베이스 아키텍처 설계 능력 검증', ARRAY['SQL','데이터베이스','DB','민간자격','전문가']),
('aws-saa', 'AWS Solutions Architect Associate', 'IT', 'Amazon Web Services', 'https://aws.amazon.com/ko/certification/certified-solutions-architect-associate/', 'AWS 클라우드 아키텍처 설계 역량 검증 자격', ARRAY['AWS','클라우드','Cloud','아키텍트','국제자격']),
('aws-sap', 'AWS Solutions Architect Professional', 'IT', 'Amazon Web Services', 'https://aws.amazon.com/ko/certification/certified-solutions-architect-professional/', 'AWS 클라우드 고급 아키텍처 설계 역량 검증 자격', ARRAY['AWS','클라우드','Cloud','아키텍트','국제자격','전문가']),
('cka', 'CKA (Kubernetes Administrator)', 'IT', 'CNCF', 'https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/', 'Kubernetes 클러스터 관리 및 운영 역량 검증', ARRAY['Kubernetes','K8s','컨테이너','DevOps','국제자격']),
('ckad', 'CKAD (Kubernetes Developer)', 'IT', 'CNCF', 'https://training.linuxfoundation.org/certification/certified-kubernetes-application-developer-ckad/', 'Kubernetes 애플리케이션 개발 역량 검증', ARRAY['Kubernetes','K8s','컨테이너','DevOps','국제자격','개발']),
('linux-master-1', '리눅스마스터 1급', 'IT', '한국정보통신진흥협회', 'https://www.ihd.or.kr/introducesubject1.do', '리눅스 시스템 관리 및 네트워크 서비스 운영 능력 검증', ARRAY['리눅스','Linux','서버','시스템','국가공인']),
('linux-master-2', '리눅스마스터 2급', 'IT', '한국정보통신진흥협회', 'https://www.ihd.or.kr/introducesubject1.do', '리눅스 시스템 기본 운영 능력 검증', ARRAY['리눅스','Linux','서버','시스템','국가공인']),
('network-admin-1', '네트워크관리사 1급', 'IT', '한국정보통신자격협회', 'https://www.icqa.or.kr/cn/page/network', '네트워크 설계, 구축, 운영 전문 능력 검증', ARRAY['네트워크','Network','인프라','민간자격']),
('network-admin-2', '네트워크관리사 2급', 'IT', '한국정보통신자격협회', 'https://www.icqa.or.kr/cn/page/network', '네트워크 기본 운영 및 관리 능력 검증', ARRAY['네트워크','Network','인프라','민간자격']),
('engineer-info-security', '정보보안기사', 'IT', '한국인터넷진흥원', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '정보보안 시스템 구축 및 운영에 관한 국가기술자격', ARRAY['보안','Security','정보보안','국가자격','기사']),
('computer-skills-1', '컴퓨터활용능력 1급', 'IT', '대한상공회의소', 'https://license.korcham.net/', '스프레드시트, 데이터베이스 고급 활용 능력 검증 국가기술자격', ARRAY['컴활','엑셀','Excel','Access','국가자격','사무']),
('computer-skills-2', '컴퓨터활용능력 2급', 'IT', '대한상공회의소', 'https://license.korcham.net/', '스프레드시트 활용 능력 검증 국가기술자격', ARRAY['컴활','엑셀','Excel','국가자격','사무']),
('word-processor', '워드프로세서', 'IT', '대한상공회의소', 'https://license.korcham.net/', '문서 작성 및 편집 능력 검증 국가기술자격', ARRAY['워드','문서작성','한글','국가자격','사무']),
('itq', 'ITQ (정보기술자격)', 'IT', '한국생산성본부', 'https://license.kpc.or.kr/nasec/qlfint/qlfint/selectItqinfotchnlgyqc.do', '한글, 엑셀, 파워포인트 등 OA 활용 능력 검증', ARRAY['OA','엑셀','파워포인트','한글','국가공인']),
-- 디자인
('gtq-1', 'GTQ 1급 (그래픽기술자격)', '디자인', '한국생산성본부', 'https://license.kpc.or.kr/nasec/qlfint/qlfint/selectGtqinfomg.do', '포토샵을 활용한 그래픽 디자인 능력 검증', ARRAY['포토샵','Photoshop','그래픽','디자인','국가공인']),
('gtq-2', 'GTQ 2급 (그래픽기술자격)', '디자인', '한국생산성본부', 'https://license.kpc.or.kr/nasec/qlfint/qlfint/selectGtqinfomg.do', '포토샵을 활용한 그래픽 디자인 기본 능력 검증', ARRAY['포토샵','Photoshop','그래픽','디자인','국가공인']),
('gtqi-1', 'GTQI 1급 (그래픽기술자격 일러스트)', '디자인', '한국생산성본부', 'https://license.kpc.or.kr/nasec/qlfint/qlfint/selectGtqinfomg.do', '일러스트를 활용한 그래픽 디자인 기본 능력 검증', ARRAY['일러스트','Illustrator','그래픽','디자인','국가공인']),
('gtqi-2', 'GTQI 2급 (그래픽기술자격 일러스트)', '디자인', '한국생산성본부', 'https://license.kpc.or.kr/nasec/qlfint/qlfint/selectGtqinfomg.do', '일러스트를 활용한 그래픽 디자인 기본 능력 검증', ARRAY['일러스트','Illustrator','그래픽','디자인','국가공인']),
('gtqid-1', 'GTQID 1급 (그래픽기술자격 인디자인)', '디자인', '한국생산성본부', 'https://license.kpc.or.kr/nasec/qlfint/qlfint/selectGtqinfomg.do', '인디자인을 활용한 그래픽 디자인 기본 능력 검증', ARRAY['인디자인','Indesign','그래픽','디자인','국가공인']),
('gtqid-2', 'GTQID 2급 (그래픽기술자격 인디자인)', '디자인', '한국생산성본부', 'https://license.kpc.or.kr/nasec/qlfint/qlfint/selectGtqinfomg.do', '인디자인을 활용한 그래픽 디자인 기본 능력 검증', ARRAY['인디자인','Indesign','그래픽','디자인','국가공인']),
-- 어학
('toeic', 'TOEIC', '어학', 'ETS', 'https://www.toeic.co.kr/', '비즈니스 영어 커뮤니케이션 능력 평가', ARRAY['영어','English','비즈니스','국제자격']),
('toeic-speaking', 'TOEIC Speaking', '어학', 'ETS', 'https://www.toeicswt.co.kr/', '영어 말하기 능력 평가', ARRAY['영어','English','스피킹','국제자격']),
('toefl', 'TOEFL iBT', '어학', 'ETS', 'https://www.ets.org/toefl', '학술 영어 능력 평가 (해외 유학용)', ARRAY['영어','English','유학','학술','국제자격']),
('opic', 'OPIc', '어학', 'ACTFL', 'https://www.opic.or.kr/', '외국어 말하기 능력 인터뷰 평가', ARRAY['영어','English','스피킹','인터뷰','국제자격']),
('jlpt', 'JLPT (일본어능력시험)', '어학', '일본국제교류기금', 'https://www.jlpt.or.kr/', '일본어 종합 능력 평가 (N1~N5)', ARRAY['일본어','Japanese','국제자격']),
('jpt', 'JPT', '어학', '한국JLPT협회', 'https://www.jpt.co.kr/', '일본어 읽기, 듣기 능력 평가', ARRAY['일본어','Japanese','민간자격']),
('hsk', 'HSK (한어수평고시)', '어학', '중국교육부', 'https://www.hsk.or.kr/', '중국어 종합 능력 평가 (1~6급)', ARRAY['중국어','Chinese','국제자격']),
('delf-dalf', 'DELF/DALF', '어학', '프랑스교육부', 'https://www.france.or.kr/', '프랑스어 능력 인증 시험', ARRAY['프랑스어','French','국제자격']),
-- 전문자격
('cpa', '공인회계사 (CPA)', '전문자격', '금융감독원', 'https://cpa.fss.or.kr/', '회계, 세무, 경영 자문 전문 자격', ARRAY['회계','세무','경영','국가자격','전문직']),
('tax-accountant', '세무사', '전문자격', '국세청', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '세무 대리 및 세무 자문 전문 자격', ARRAY['세무','세금','국가자격','전문직']),
('lawyer', '변호사', '전문자격', '법무부', 'https://www.moj.go.kr/', '법률 사무 전반에 관한 전문 자격', ARRAY['법률','법무','국가자격','전문직']),
('patent-attorney', '변리사', '전문자격', '특허청', 'https://www.kipo.go.kr/', '특허, 상표, 디자인 등 지적재산권 전문 자격', ARRAY['특허','지적재산권','국가자격','전문직']),
('appraiser', '감정평가사', '전문자격', '국토교통부', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '부동산 등 재산 가치 평가 전문 자격', ARRAY['감정평가','부동산','국가자격','전문직']),
('labor-attorney', '공인노무사', '전문자격', '고용노동부', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '노동관계 법령에 따른 업무 대행 전문 자격', ARRAY['노무','노동법','인사','국가자격','전문직']),
('customs-broker', '관세사', '전문자격', '관세청', 'https://www.customs.go.kr/', '수출입 통관 및 관세 업무 전문 자격', ARRAY['관세','무역','수출입','국가자격','전문직']),
('judicial-scrivener', '법무사', '전문자격', '법무부', 'https://www.moj.go.kr/', '등기, 공탁 등 법률 문서 작성 전문 자격', ARRAY['등기','법률','문서','국가자격','전문직']),
-- 기술
('engineer-electrical', '전기기사', '기술', '한국산업인력공단', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '전기설비 설계, 시공, 운영에 관한 국가기술자격', ARRAY['전기','설비','국가자격','기사']),
('engineer-electrical-industrial', '전기산업기사', '기술', '한국산업인력공단', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '전기설비 시공, 운영에 관한 산업기사 수준 국가기술자격', ARRAY['전기','설비','국가자격','산업기사']),
('engineer-architecture', '건축기사', '기술', '한국산업인력공단', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '건축물 설계, 시공, 감리에 관한 국가기술자격', ARRAY['건축','설계','시공','국가자격','기사']),
('engineer-civil', '토목기사', '기술', '한국산업인력공단', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '토목 구조물 설계, 시공에 관한 국가기술자격', ARRAY['토목','건설','국가자격','기사']),
('engineer-mechanical', '일반기계기사', '기술', '한국산업인력공단', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '기계설비 설계, 제작, 설치에 관한 국가기술자격', ARRAY['기계','설계','제작','국가자격','기사']),
('engineer-fire', '소방설비기사', '기술', '한국산업인력공단', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '소방설비 설계, 시공, 감리에 관한 국가기술자격', ARRAY['소방','안전','설비','국가자격','기사']),
('engineer-safety', '산업안전기사', '기술', '한국산업인력공단', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '산업 현장 안전관리에 관한 국가기술자격', ARRAY['안전','산업안전','국가자격','기사']),
('engineer-environmental', '환경기사', '기술', '한국산업인력공단', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '환경오염 방지 및 환경관리에 관한 국가기술자격', ARRAY['환경','환경관리','국가자격','기사']),
-- 금융
('computerized-accounting-1', '전산회계 1급', '금융', '한국세무사회', 'https://license.kacpta.or.kr/', '전산회계 프로그램을 활용한 회계 실무 능력 검증', ARRAY['회계','세무','전산','국가공인']),
('computerized-accounting-2', '전산회계 2급', '금융', '한국세무사회', 'https://license.kacpta.or.kr/', '전산회계 프로그램을 활용한 기초 회계 실무 능력 검증', ARRAY['회계','세무','전산','국가공인']),
('computerized-tax-1', '전산세무 1급', '금융', '한국세무사회', 'https://license.kacpta.or.kr/', '전산세무 프로그램을 활용한 세무 실무 전문 능력 검증', ARRAY['세무','회계','전산','국가공인']),
('computerized-tax-2', '전산세무 2급', '금융', '한국세무사회', 'https://license.kacpta.or.kr/', '전산세무 프로그램을 활용한 세무 실무 능력 검증', ARRAY['세무','회계','전산','국가공인']),
('fat-1', 'FAT 1급 (회계실무)', '금융', '한국공인회계사회', 'https://at.kicpa.or.kr/', '회계정보 처리 및 활용 능력 검증 (회계실무 1급)', ARRAY['회계','FAT','AT자격','민간자격']),
('fat-2', 'FAT 2급 (회계실무)', '금융', '한국공인회계사회', 'https://at.kicpa.or.kr/', '회계정보 처리 기초 능력 검증 (회계실무 2급)', ARRAY['회계','FAT','AT자격','민간자격']),
('tat-1', 'TAT 1급 (세무실무)', '금융', '한국공인회계사회', 'https://at.kicpa.or.kr/', '세무정보 처리 및 활용 전문 능력 검증 (세무실무 1급)', ARRAY['세무','TAT','AT자격','민간자격']),
('tat-2', 'TAT 2급 (세무실무)', '금융', '한국공인회계사회', 'https://at.kicpa.or.kr/', '세무정보 처리 능력 검증 (세무실무 2급)', ARRAY['세무','TAT','AT자격','민간자격']),
('accounting-operator', '회계운용사', '금융', '대한상공회의소', 'https://license.korcham.net/', '기업 회계 실무 능력 검증 국가기술자격', ARRAY['회계','경리','사무','국가자격']),
('cfa', 'CFA (Chartered Financial Analyst)', '금융', 'CFA Institute', 'https://www.cfainstitute.org/', '투자 분석 및 자산운용 전문 국제 자격', ARRAY['투자','자산운용','금융','국제자격','전문가']),
('frm', 'FRM (Financial Risk Manager)', '금융', 'GARP', 'https://www.garp.org/frm', '금융 리스크 관리 전문 국제 자격', ARRAY['리스크','위험관리','금융','국제자격']),
('investment-asset-manager', '투자자산운용사', '금융', '금융투자협회', 'https://license.kofia.or.kr/', '집합투자재산, 신탁재산 운용 업무 수행 자격', ARRAY['투자','자산운용','펀드','국가공인']),
('fund-investment-advisor', '펀드투자권유자문인력', '금융', '금융투자협회', 'https://license.kofia.or.kr/', '펀드 투자 권유 및 자문 업무 수행 자격', ARRAY['펀드','투자','자문','국가공인']),
('securities-investment-advisor', '증권투자권유자문인력', '금융', '금융투자협회', 'https://license.kofia.or.kr/', '증권 투자 권유 업무 수행 자격', ARRAY['증권','투자','주식','국가공인']),
('derivatives-investment-advisor', '파생상품투자권유자문인력', '금융', '금융투자협회', 'https://license.kofia.or.kr/', '파생상품 투자 권유 업무 수행 자격', ARRAY['파생상품','선물','옵션','국가공인']),
('afpk', 'AFPK (재무설계사)', '금융', '한국FPSB', 'https://www.fpsbkorea.org/', '개인 재무설계 전문 자격', ARRAY['재무설계','FP','자산관리','민간자격']),
('cfp', 'CFP (국제재무설계사)', '금융', 'FPSB', 'https://www.fpsbkorea.org/', '재무설계 전문가 국제 자격', ARRAY['재무설계','FP','자산관리','국제자격','전문가']),
-- 기타
('barista-1', '바리스타 1급', '기타', '한국커피협회', 'https://www.kca.or.kr/', '커피 추출 및 서비스 전문 자격', ARRAY['커피','바리스타','민간자격']),
('korean-history-1', '한국사능력검정시험 1급', '기타', '국사편찬위원회', 'https://www.historyexam.go.kr/', '한국사 이해 능력 검증 국가시험', ARRAY['한국사','역사','국가시험']),
('korean-history-2', '한국사능력검정시험 2급', '기타', '국사편찬위원회', 'https://www.historyexam.go.kr/', '한국사 이해 능력 검증 국가시험', ARRAY['한국사','역사','국가시험']),
('driving-license-1', '운전면허 1종', '기타', '경찰청', 'https://www.safedriving.or.kr/', '승용차, 승합차, 화물차 운전 자격', ARRAY['운전','면허','국가자격']),
('cooking-korean', '한식조리기능사', '기타', '한국산업인력공단', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '한식 조리에 관한 국가기술자격', ARRAY['조리','요리','한식','국가자격','기능사']),
('welfare-worker-1', '사회복지사 1급', '기타', '한국사회복지사협회', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '사회복지 전문 업무 수행 자격', ARRAY['복지','사회복지','국가자격']),
-- 추가: 시험일정 크롤링에서 사용되는 자격증
('craftsman-info-processing', '정보처리기능사', 'IT', '한국산업인력공단', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '정보처리 분야 기능사 수준 국가기술자격', ARRAY['국가자격','정보처리','IT','기능사']),
('craftsman-electrical', '전기기능사', '기술', '한국산업인력공단', 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&gId=', '전기설비 기초 실무에 관한 국가기술자격', ARRAY['전기','설비','국가자격','기능사']),
('adsp', 'ADsP (데이터분석 준전문가)', 'IT', '한국데이터산업진흥원', 'https://www.dataq.or.kr/', '데이터 분석 기획 및 활용 능력 검증 준전문가 자격', ARRAY['데이터','분석','빅데이터','민간자격']),
('bigdata-engineer', '빅데이터분석기사', 'IT', '한국데이터산업진흥원', 'https://www.dataq.or.kr/', '빅데이터 수집·저장·처리·분석에 관한 국가기술자격', ARRAY['빅데이터','데이터분석','AI','국가자격','기사']);
